ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER BREADONBOARD IDENTIFIED BY BREADONBOARD;

CREATE SEQUENCE BREADONBOARD.ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOORDER;

CREATE SEQUENCE BREADONBOARD.RECIPE_SEQ START WITH 1 INCREMENT BY 1 NOORDER;

CREATE SEQUENCE BREADONBOARD.RECIPE_STEP_SEQ START WITH 1 INCREMENT BY 1 NOORDER;

CREATE  TABLE BREADONBOARD.ACCOUNT ( 
	ID                   VARCHAR2(5)   NOT NULL,
	USERNAME             VARCHAR2(100)   NOT NULL,
	MAIL_ADDRESS         VARCHAR2(1000)   NOT NULL,
	PASSWORD             VARCHAR2(100)   NOT NULL,
	CONSTRAINT PK_ACCOUNT PRIMARY KEY ( ID ) 
 );

CREATE  TABLE BREADONBOARD.RECIPE ( 
	ID                   VARCHAR2(6)   NOT NULL,
	ACCOUNT_ID           VARCHAR2(5)   NOT NULL,
	TITLE                VARCHAR2(2000)   NOT NULL,
	IMAGE                VARCHAR2(1000)   ,
	INGREDIENTS          VARCHAR2(2000)   ,
	CONSTRAINT PK_RECIPE PRIMARY KEY ( ID ) 
 );

CREATE  TABLE BREADONBOARD.RECIPE_STEP ( 
	ID                   VARCHAR2(7)   NOT NULL,
	RECIPE_ID            VARCHAR2(6)   NOT NULL,
	TEXT                 VARCHAR2(1000)   NOT NULL,
	STEP_ORDER           INTEGER   NOT NULL,
	"SYS_C00004_24110514:06:57$" INTEGER   ,
	CONSTRAINT PK_RECIPESTEP PRIMARY KEY ( ID ) 
 );

ALTER TABLE BREADONBOARD.RECIPE ADD CONSTRAINT FK_RECIPE_ACCOUNT FOREIGN KEY ( ACCOUNT_ID ) REFERENCES BREADONBOARD.ACCOUNT( ID ) ON DELETE CASCADE;

ALTER TABLE BREADONBOARD.RECIPE_STEP ADD CONSTRAINT FK_RECIPESTEP_RECIPE FOREIGN KEY ( RECIPE_ID ) REFERENCES BREADONBOARD.RECIPE( ID );
